name: github-context-printing value

on: workflow_dispatch

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Display GitHub repository
        run: echo "Repository ${{github.repository}}"
      - name: Display GitHub repository
        run: echo "Repository ${{github}}"
    

