on: [push]

jobs:
  call_compose_action:
    runs-on: ubuntu-latest
    steps:
        - uses: action/checkout@v3
        - uses: pvmtriet232/hello-world-composite-action@v1
        - run: echo random-number
